### ISSUE TITLE
Current builds of docs result in blank page

### ISSUE THREAD

**Issue by mithro** [im-tomu/fomu-workshop#827]
You get the following in the javascript console;
```
sphinx_symbiflow_theme.js:1 Uncaught ReferenceError: $ is not defined
    at parcelRequire.GG8f.../scss/sphinx_symbiflow_theme.scss (sphinx_symbiflow_theme.js:703:234)
    at f (sphinx_symbiflow_theme.js:1:468)
    at parcelRequire.QtPh (sphinx_symbiflow_theme.js:1:771)
    at sphinx_symbiflow_theme.js:1:1023
```

**Comment by kgugala** [comment]
This has been fixed with https://github.com/im-tomu/fomu-workshop/commit/8e9aa0a6df8629213679298fee77c63792bd63ac
